apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-management-app.frontend.fullname" . }}
  namespace: {{ .Values.frontend.namespace }}
  labels:
    {{- include "user-management-app.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "user-management-app.frontend.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.frontend.service.type "LoadBalancer" }}
  {{- with .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}